packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  ' ': true
  b: true
  bcrypt: false
  c: true
  d: true
  e: true
  esbuild: false
  i: true
  l: true
  p: true
  r: true
  s: true
  t: true
  u: true
  y: true
